modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
[[mods]]
modId="thiamod"
version="1.0"
displayName="ThiaMod"
logoFile="examplemod.png"
credits="Pão de batata"
authors="Thiago"
description='''
Certamente um mod.
'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
